version: '3.8'
services:
  caddy:
    image: pisethk123/cadddy:1.0
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    depends_on:
      - express
    networks:
      - mern

  express:
    image: pisethk123/server:12.0
    restart: unless-stopped
    ports:
      - 8000:8000
    networks:
      - mern
networks:
  mern:
    driver: bridge
